apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  labels:
    app: search
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
      - name: search
        image: wartexnik/search:latest
        ports:
        - containerPort: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: search
  labels:
    app: search
spec:
  type: LoadBalancer
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
  selector:
    app: search